use c_enum::c_enum;
use cupti_sys::*;

c_enum! {
    pub enum NvtxApiTraceCbid : CUpti_nvtx_api_trace_cbid {
        INVALID = CUPTI_CBID_NVTX_INVALID,
        nvtxMarkA = CUPTI_CBID_NVTX_nvtxMarkA,
        nvtxMarkW = CUPTI_CBID_NVTX_nvtxMarkW,
        nvtxMarkEx = CUPTI_CBID_NVTX_nvtxMarkEx,
        nvtxRangeStartA = CUPTI_CBID_NVTX_nvtxRangeStartA,
        nvtxRangeStartW = CUPTI_CBID_NVTX_nvtxRangeStartW,
        nvtxRangeStartEx = CUPTI_CBID_NVTX_nvtxRangeStartEx,
        nvtxRangeEnd = CUPTI_CBID_NVTX_nvtxRangeEnd,
        nvtxRangePushA = CUPTI_CBID_NVTX_nvtxRangePushA,
        nvtxRangePushW = CUPTI_CBID_NVTX_nvtxRangePushW,
        nvtxRangePushEx = CUPTI_CBID_NVTX_nvtxRangePushEx,
        nvtxRangePop = CUPTI_CBID_NVTX_nvtxRangePop,
        nvtxNameCategoryA = CUPTI_CBID_NVTX_nvtxNameCategoryA,
        nvtxNameCategoryW = CUPTI_CBID_NVTX_nvtxNameCategoryW,
        nvtxNameOsThreadA = CUPTI_CBID_NVTX_nvtxNameOsThreadA,
        nvtxNameOsThreadW = CUPTI_CBID_NVTX_nvtxNameOsThreadW,
        nvtxNameCuDeviceA = CUPTI_CBID_NVTX_nvtxNameCuDeviceA,
        nvtxNameCuDeviceW = CUPTI_CBID_NVTX_nvtxNameCuDeviceW,
        nvtxNameCuContextA = CUPTI_CBID_NVTX_nvtxNameCuContextA,
        nvtxNameCuContextW = CUPTI_CBID_NVTX_nvtxNameCuContextW,
        nvtxNameCuStreamA = CUPTI_CBID_NVTX_nvtxNameCuStreamA,
        nvtxNameCuStreamW = CUPTI_CBID_NVTX_nvtxNameCuStreamW,
        nvtxNameCuEventA = CUPTI_CBID_NVTX_nvtxNameCuEventA,
        nvtxNameCuEventW = CUPTI_CBID_NVTX_nvtxNameCuEventW,
        nvtxNameCudaDeviceA = CUPTI_CBID_NVTX_nvtxNameCudaDeviceA,
        nvtxNameCudaDeviceW = CUPTI_CBID_NVTX_nvtxNameCudaDeviceW,
        nvtxNameCudaStreamA = CUPTI_CBID_NVTX_nvtxNameCudaStreamA,
        nvtxNameCudaStreamW = CUPTI_CBID_NVTX_nvtxNameCudaStreamW,
        nvtxNameCudaEventA = CUPTI_CBID_NVTX_nvtxNameCudaEventA,
        nvtxNameCudaEventW = CUPTI_CBID_NVTX_nvtxNameCudaEventW,
        nvtxDomainMarkEx = CUPTI_CBID_NVTX_nvtxDomainMarkEx,
        nvtxDomainRangeStartEx = CUPTI_CBID_NVTX_nvtxDomainRangeStartEx,
        nvtxDomainRangeEnd = CUPTI_CBID_NVTX_nvtxDomainRangeEnd,
        nvtxDomainRangePushEx = CUPTI_CBID_NVTX_nvtxDomainRangePushEx,
        nvtxDomainRangePop = CUPTI_CBID_NVTX_nvtxDomainRangePop,
        nvtxDomainResourceCreate = CUPTI_CBID_NVTX_nvtxDomainResourceCreate,
        nvtxDomainResourceDestroy = CUPTI_CBID_NVTX_nvtxDomainResourceDestroy,
        nvtxDomainNameCategoryA = CUPTI_CBID_NVTX_nvtxDomainNameCategoryA,
        nvtxDomainNameCategoryW = CUPTI_CBID_NVTX_nvtxDomainNameCategoryW,
        nvtxDomainRegisterStringA = CUPTI_CBID_NVTX_nvtxDomainRegisterStringA,
        nvtxDomainRegisterStringW = CUPTI_CBID_NVTX_nvtxDomainRegisterStringW,
        nvtxDomainCreateA = CUPTI_CBID_NVTX_nvtxDomainCreateA,
        nvtxDomainCreateW = CUPTI_CBID_NVTX_nvtxDomainCreateW,
        nvtxDomainDestroy = CUPTI_CBID_NVTX_nvtxDomainDestroy,
        nvtxDomainSyncUserCreate = CUPTI_CBID_NVTX_nvtxDomainSyncUserCreate,
        nvtxDomainSyncUserDestroy = CUPTI_CBID_NVTX_nvtxDomainSyncUserDestroy,
        nvtxDomainSyncUserAcquireStart = CUPTI_CBID_NVTX_nvtxDomainSyncUserAcquireStart,
        nvtxDomainSyncUserAcquireFailed = CUPTI_CBID_NVTX_nvtxDomainSyncUserAcquireFailed,
        nvtxDomainSyncUserAcquireSuccess = CUPTI_CBID_NVTX_nvtxDomainSyncUserAcquireSuccess,
        nvtxDomainSyncUserReleasing = CUPTI_CBID_NVTX_nvtxDomainSyncUserReleasing,
    }
}
